Importing necessary libraries.

In [2]:
import tensorflow
import pandas as pd
import plotly.express as px
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from keras.models import Sequential
from keras.layers import Dense, LSTM
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dropout
import numpy as np

In [3]:
import yfinance as yf
import datetime

Accessing today's date using datetime.

In [4]:
today = datetime.datetime.now()
today
date_today = today.strftime("%Y-%m-%d")

In [5]:
date_today

'2023-11-29'

Using 'ETH-USD' ticker to get data from start date to today.

In [6]:
ticker = 'AMZN'
end_date = date_today
start_date = '2015-01-01'

Downloading data and converting it into a pandas dataframe.

In [7]:
df = yf.download(ticker, start = start_date, end = end_date)

[*********************100%%**********************]  1 of 1 completed


In [8]:
df

Open        High         Low       Close   Adj Close  \
Date                                                                     
2015-01-02   15.629000   15.737500   15.348000   15.426000   15.426000   
2015-01-05   15.350500   15.419000   15.042500   15.109500   15.109500   
2015-01-06   15.112000   15.150000   14.619000   14.764500   14.764500   
2015-01-07   14.875000   15.064000   14.766500   14.921000   14.921000   
2015-01-08   15.016000   15.157000   14.805500   15.023000   15.023000   
...                ...         ...         ...         ...         ...   
2023-11-21  143.910004  144.050003  141.500000  143.899994  143.899994   
2023-11-22  144.570007  147.740005  144.570007  146.710007  146.710007   
2023-11-24  146.699997  147.199997  145.320007  146.740005  146.740005   
2023-11-27  147.529999  149.259995  146.880005  147.729996  147.729996   
2023-11-28  146.979996  147.600006  145.529999  147.029999  147.029999   

              Volume  
Date                  
2015-01-02  55664000  
2015-01-05  55484000  
2015-01-06  70380000  
2015-01-07  52806000  
2015-01-08  61768000  
...              ...  
2023-11-21  71226000  
2023-11-22  45669100  
2023-11-24  22378400  
2023-11-27  53762400  
2023-11-28  42612600  

[2242 rows x 6 columns]

In [9]:
import pandas as pd
data = pd.DataFrame(df)

In [10]:
data

Open        High         Low       Close   Adj Close  \
Date                                                                     
2015-01-02   15.629000   15.737500   15.348000   15.426000   15.426000   
2015-01-05   15.350500   15.419000   15.042500   15.109500   15.109500   
2015-01-06   15.112000   15.150000   14.619000   14.764500   14.764500   
2015-01-07   14.875000   15.064000   14.766500   14.921000   14.921000   
2015-01-08   15.016000   15.157000   14.805500   15.023000   15.023000   
...                ...         ...         ...         ...         ...   
2023-11-21  143.910004  144.050003  141.500000  143.899994  143.899994   
2023-11-22  144.570007  147.740005  144.570007  146.710007  146.710007   
2023-11-24  146.699997  147.199997  145.320007  146.740005  146.740005   
2023-11-27  147.529999  149.259995  146.880005  147.729996  147.729996   
2023-11-28  146.979996  147.600006  145.529999  147.029999  147.029999   

              Volume  
Date                  
2015-01-02  55664000  
2015-01-05  55484000  
2015-01-06  70380000  
2015-01-07  52806000  
2015-01-08  61768000  
...              ...  
2023-11-21  71226000  
2023-11-22  45669100  
2023-11-24  22378400  
2023-11-27  53762400  
2023-11-28  42612600  

[2242 rows x 6 columns]

Seperating date column and seperating it into new columns Month,Year and day

In [11]:
data['Date'] = pd.to_datetime(data.index).date

In [12]:
data = data.reset_index(drop=True)
data

Open        High         Low       Close   Adj Close    Volume  \
0      15.629000   15.737500   15.348000   15.426000   15.426000  55664000   
1      15.350500   15.419000   15.042500   15.109500   15.109500  55484000   
2      15.112000   15.150000   14.619000   14.764500   14.764500  70380000   
3      14.875000   15.064000   14.766500   14.921000   14.921000  52806000   
4      15.016000   15.157000   14.805500   15.023000   15.023000  61768000   
...          ...         ...         ...         ...         ...       ...   
2237  143.910004  144.050003  141.500000  143.899994  143.899994  71226000   
2238  144.570007  147.740005  144.570007  146.710007  146.710007  45669100   
2239  146.699997  147.199997  145.320007  146.740005  146.740005  22378400   
2240  147.529999  149.259995  146.880005  147.729996  147.729996  53762400   
2241  146.979996  147.600006  145.529999  147.029999  147.029999  42612600   

            Date  
0     2015-01-02  
1     2015-01-05  
2     2015-01-06  
3     2015-01-07  
4     2015-01-08  
...          ...  
2237  2023-11-21  
2238  2023-11-22  
2239  2023-11-24  
2240  2023-11-27  
2241  2023-11-28  

[2242 rows x 7 columns]

In [13]:
data['Month'] = pd.to_datetime(data['Date']).dt.month

In [14]:
data['Year'] = pd.to_datetime(data['Date']).dt.year
data['day'] = pd.to_datetime(data['Date']).dt.day

In [15]:
data

Open        High         Low       Close   Adj Close    Volume  \
0      15.629000   15.737500   15.348000   15.426000   15.426000  55664000   
1      15.350500   15.419000   15.042500   15.109500   15.109500  55484000   
2      15.112000   15.150000   14.619000   14.764500   14.764500  70380000   
3      14.875000   15.064000   14.766500   14.921000   14.921000  52806000   
4      15.016000   15.157000   14.805500   15.023000   15.023000  61768000   
...          ...         ...         ...         ...         ...       ...   
2237  143.910004  144.050003  141.500000  143.899994  143.899994  71226000   
2238  144.570007  147.740005  144.570007  146.710007  146.710007  45669100   
2239  146.699997  147.199997  145.320007  146.740005  146.740005  22378400   
2240  147.529999  149.259995  146.880005  147.729996  147.729996  53762400   
2241  146.979996  147.600006  145.529999  147.029999  147.029999  42612600   

            Date  Month  Year  day  
0     2015-01-02      1  2015    2  
1     2015-01-05      1  2015    5  
2     2015-01-06      1  2015    6  
3     2015-01-07      1  2015    7  
4     2015-01-08      1  2015    8  
...          ...    ...   ...  ...  
2237  2023-11-21     11  2023   21  
2238  2023-11-22     11  2023   22  
2239  2023-11-24     11  2023   24  
2240  2023-11-27     11  2023   27  
2241  2023-11-28     11  2023   28  

[2242 rows x 10 columns]

Using scatter plot to gain insight about closing value throughtout the dataset and analyzing pattern.

In [16]:
px.scatter(data,x=data['Date'],y=data['Close'])

Using color coding for different Years.

In [17]:
px.scatter(data,x=data['Date'],y=data['Close'],color = 'Year')

As the dataset is a timeseries data we are using open, high, lo, close columns for both input and output variables.

In [18]:
x = data[['Open','High','Low','Close']].values
y = data[['Open','High','Low','Close']].values

Splitting the data into training and testing data.

In [19]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=180)

In [20]:
n_features = x_train.shape
n_features

(1569, 4)

Creating a LSTM model based on the input and output variables.

In [21]:
# create and fit the LSTM network
model3 = Sequential()
model3.add(LSTM(120, activation='relu', return_sequences=True, input_shape=(4, 1)))
model3.add(LSTM(120, activation='relu'))
model3.add(Dense(80, activation='linear'))
model3.add(Dense(4, activation='linear'))
model3.compile(loss='MeanSquaredError', optimizer='adam', metrics=['accuracy'])
model3.fit(x, y, epochs=10, batch_size=10, verbose=2)


Epoch 1/10
225/225 - 6s - loss: 429.3743 - accuracy: 0.5825 - 6s/epoch - 26ms/step
Epoch 2/10
225/225 - 2s - loss: 0.9020 - accuracy: 0.9692 - 2s/epoch - 8ms/step
Epoch 3/10
225/225 - 2s - loss: 0.9593 - accuracy: 0.9581 - 2s/epoch - 8ms/step
Epoch 4/10
225/225 - 2s - loss: 0.9796 - accuracy: 0.9023 - 2s/epoch - 8ms/step
Epoch 5/10
225/225 - 2s - loss: 0.9832 - accuracy: 0.8921 - 2s/epoch - 10ms/step
Epoch 6/10
225/225 - 3s - loss: 1.0708 - accuracy: 0.8537 - 3s/epoch - 12ms/step
Epoch 7/10
225/225 - 2s - loss: 0.9555 - accuracy: 0.8796 - 2s/epoch - 7ms/step
Epoch 8/10
225/225 - 2s - loss: 0.9590 - accuracy: 0.9224 - 2s/epoch - 8ms/step
Epoch 9/10
225/225 - 2s - loss: 1.0727 - accuracy: 0.8880 - 2s/epoch - 8ms/step
Epoch 10/10
225/225 - 2s - loss: 0.9318 - accuracy: 0.8327 - 2s/epoch - 7ms/step


Testing model performance for the testing data.

In [22]:
y_pred = model3.predict(x_test)

22/22 [==============================] - 0s 6ms/step


In [23]:
y_pred.shape

(673, 4)

Reshaping the predicted output into the input(testing data) shape.

In [24]:
y_pred=y_pred.reshape(y_test.shape)

In [25]:
y_test.shape

(673, 4)

In [26]:
y_pred.shape

(673, 4)

Calculating the difference between actual and predicted output.

In [27]:
diff = y_test[:,2:3] - y_pred[:,2:3]

In [28]:
diff

array([[-3.22921753e-01],
       [-8.45756531e-01],
       [-1.59980774e-01],
       [-1.64265442e+00],
       [-1.32308960e-01],
       [ 5.65437317e-01],
       [ 6.43157959e-01],
       [ 3.75564575e-01],
       [ 3.24096680e-01],
       [ 9.50851440e-02],
       [-8.10165405e-01],
       [ 1.36413574e-02],
       [ 4.91615295e-01],
       [-1.13250732e-01],
       [-1.31203461e+00],
       [-9.71755981e-02],
       [-3.21838379e-01],
       [-1.74926758e+00],
       [-1.46171570e-01],
       [-3.06777954e-01],
       [ 5.33126831e-01],
       [-1.27323151e-01],
       [-1.87814331e+00],
       [-8.52355957e-02],
       [-3.06518555e-01],
       [-1.84268951e-01],
       [ 4.20806885e-01],
       [-4.49554443e-01],
       [-7.77359009e-02],
       [ 5.27557373e-01],
       [-5.61073303e-01],
       [ 1.02943420e-01],
       [-2.28424072e-01],
       [-2.64694977e+00],
       [ 6.11953735e-02],
       [-1.18347168e-01],
       [-2.99242020e-01],
       [ 3.76647949e-01],
       [ 1.3

Plotting te difference using scatter plot.

In [29]:
px.scatter(diff)

In [30]:
n = 10 #n represents the number of days we need forecast for.

In [31]:
last = list(data.iloc[-1,0:4]) #creating a list and adding the last day open, high, low, close values.

In [32]:
last

[146.97999572753906,
 147.60000610351562,
 145.52999877929688,
 147.02999877929688]

In [33]:
model3.predict([last]) #predicting the forecast of next day using the last day.

1/1 [==============================] - 0s 41ms/step


array([[146.42604, 148.62398, 145.43355, 147.25856]], dtype=float32)

In [34]:
forecastn = [last] #ceating a new list forecastn to store the forecast of n days.

predicting for nth day forecast using predicted value of n-1th day.

In [35]:
for i in range(1,n+1):
  forecastn.append(model3.predict([forecastn[i-1]]))

1/1 [==============================] - 0s 43ms/step


In [36]:
forecastn

[[146.97999572753906,
  147.60000610351562,
  145.52999877929688,
  147.02999877929688],
 array([[146.42604, 148.62398, 145.43355, 147.25856]], dtype=float32),
 array([[146.44736, 148.71492, 145.5181 , 147.40573]], dtype=float32),
 array([[146.50017, 148.79205, 145.59673, 147.5078 ]], dtype=float32),
 array([[146.5645 , 148.86653, 145.67105, 147.59186]], dtype=float32),
 array([[146.63338, 148.94002, 145.74368, 147.66887]], dtype=float32),
 array([[146.70403, 149.01308, 145.81567, 147.74315]], dtype=float32),
 array([[146.77527, 149.08606, 145.88739, 147.81639]], dtype=float32),
 array([[146.84683, 149.159  , 145.95901, 147.88922]], dtype=float32),
 array([[146.91849, 149.23184, 146.03064, 147.96185]], dtype=float32),
 array([[146.99023, 149.30473, 146.10225, 148.03444]], dtype=float32)]

In [37]:
forecastn.pop(0) #Removing the last day values from the forecast.

[146.97999572753906,
 147.60000610351562,
 145.52999877929688,
 147.02999877929688]

Seperating just closing values from the forecast.

In [38]:
extra = [arr[0][2:3] for arr in forecastn]
extra

[array([145.43355], dtype=float32),
 array([145.5181], dtype=float32),
 array([145.59673], dtype=float32),
 array([145.67105], dtype=float32),
 array([145.74368], dtype=float32),
 array([145.81567], dtype=float32),
 array([145.88739], dtype=float32),
 array([145.95901], dtype=float32),
 array([146.03064], dtype=float32),
 array([146.10225], dtype=float32)]

Converting the numpy values into float values and adding them to a list.

In [39]:
for i in range(len(extra)):
  extra[i] = list(extra[i])

In [40]:
extra1 = [arr[0] for arr in extra]

In [41]:
extra1

[145.43355,
 145.5181,
 145.59673,
 145.67105,
 145.74368,
 145.81567,
 145.88739,
 145.95901,
 146.03064,
 146.10225]

Closing value of the nth day based on the forecast.

In [42]:
print(extra1[-1])

146.10225


In [43]:
px.line(x=extra1)

In [44]:
import pickle
with open('model3.pkl', 'wb') as file:
    pickle.dump(model3, file)

In [1]:
with open('model3.pkl', 'rb') as file:
    model3 = pickle.load(file)

FileNotFoundError: ignored