Importing necessary libraries.

In [1]:
import tensorflow
import pandas as pd
import plotly.express as px
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from keras.models import Sequential
from keras.layers import Dense, LSTM
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dropout
import numpy as np

In [2]:
import yfinance as yf
import datetime

Accessing today's date using datetime.

In [3]:
today = datetime.datetime.now()
today
date_today = today.strftime("%Y-%m-%d")

In [4]:
date_today

'2023-11-29'

Using 'ETH-USD' ticker to get data from start date to today.

In [5]:
ticker = 'AAPL'
end_date = date_today
start_date = '2015-01-01'

Downloading data and converting it into a pandas dataframe.

In [6]:
df = yf.download(ticker, start = start_date, end = end_date)

[*********************100%%**********************]  1 of 1 completed


In [7]:
df

Open        High         Low       Close   Adj Close  \
Date                                                                     
2015-01-02   27.847500   27.860001   26.837500   27.332500   24.466448   
2015-01-05   27.072500   27.162500   26.352501   26.562500   23.777191   
2015-01-06   26.635000   26.857500   26.157499   26.565001   23.779430   
2015-01-07   26.799999   27.049999   26.674999   26.937500   24.112871   
2015-01-08   27.307501   28.037500   27.174999   27.972500   25.039339   
...                ...         ...         ...         ...         ...   
2023-11-21  191.410004  191.520004  189.740005  190.639999  190.639999   
2023-11-22  191.490005  192.929993  190.830002  191.309998  191.309998   
2023-11-24  190.869995  190.899994  189.250000  189.970001  189.970001   
2023-11-27  189.919998  190.669998  188.899994  189.789993  189.789993   
2023-11-28  189.779999  191.080002  189.399994  190.399994  190.399994   

               Volume  
Date                   
2015-01-02  212818400  
2015-01-05  257142000  
2015-01-06  263188400  
2015-01-07  160423600  
2015-01-08  237458000  
...               ...  
2023-11-21   38134500  
2023-11-22   39617700  
2023-11-24   24048300  
2023-11-27   40552600  
2023-11-28   38368300  

[2242 rows x 6 columns]

In [8]:
import pandas as pd
data = pd.DataFrame(df)

In [9]:
data

Open        High         Low       Close   Adj Close  \
Date                                                                     
2015-01-02   27.847500   27.860001   26.837500   27.332500   24.466448   
2015-01-05   27.072500   27.162500   26.352501   26.562500   23.777191   
2015-01-06   26.635000   26.857500   26.157499   26.565001   23.779430   
2015-01-07   26.799999   27.049999   26.674999   26.937500   24.112871   
2015-01-08   27.307501   28.037500   27.174999   27.972500   25.039339   
...                ...         ...         ...         ...         ...   
2023-11-21  191.410004  191.520004  189.740005  190.639999  190.639999   
2023-11-22  191.490005  192.929993  190.830002  191.309998  191.309998   
2023-11-24  190.869995  190.899994  189.250000  189.970001  189.970001   
2023-11-27  189.919998  190.669998  188.899994  189.789993  189.789993   
2023-11-28  189.779999  191.080002  189.399994  190.399994  190.399994   

               Volume  
Date                   
2015-01-02  212818400  
2015-01-05  257142000  
2015-01-06  263188400  
2015-01-07  160423600  
2015-01-08  237458000  
...               ...  
2023-11-21   38134500  
2023-11-22   39617700  
2023-11-24   24048300  
2023-11-27   40552600  
2023-11-28   38368300  

[2242 rows x 6 columns]

Seperating date column and seperating it into new columns Month,Year and day

In [10]:
data['Date'] = pd.to_datetime(data.index).date

In [11]:
data = data.reset_index(drop=True)
data

Open        High         Low       Close   Adj Close     Volume  \
0      27.847500   27.860001   26.837500   27.332500   24.466448  212818400   
1      27.072500   27.162500   26.352501   26.562500   23.777191  257142000   
2      26.635000   26.857500   26.157499   26.565001   23.779430  263188400   
3      26.799999   27.049999   26.674999   26.937500   24.112871  160423600   
4      27.307501   28.037500   27.174999   27.972500   25.039339  237458000   
...          ...         ...         ...         ...         ...        ...   
2237  191.410004  191.520004  189.740005  190.639999  190.639999   38134500   
2238  191.490005  192.929993  190.830002  191.309998  191.309998   39617700   
2239  190.869995  190.899994  189.250000  189.970001  189.970001   24048300   
2240  189.919998  190.669998  188.899994  189.789993  189.789993   40552600   
2241  189.779999  191.080002  189.399994  190.399994  190.399994   38368300   

            Date  
0     2015-01-02  
1     2015-01-05  
2     2015-01-06  
3     2015-01-07  
4     2015-01-08  
...          ...  
2237  2023-11-21  
2238  2023-11-22  
2239  2023-11-24  
2240  2023-11-27  
2241  2023-11-28  

[2242 rows x 7 columns]

In [12]:
data['Month'] = pd.to_datetime(data['Date']).dt.month

In [13]:
data['Year'] = pd.to_datetime(data['Date']).dt.year
data['day'] = pd.to_datetime(data['Date']).dt.day

In [ ]:
data

Open        High         Low       Close   Adj Close     Volume  \
0      27.847500   27.860001   26.837500   27.332500   24.466448  212818400   
1      27.072500   27.162500   26.352501   26.562500   23.777189  257142000   
2      26.635000   26.857500   26.157499   26.565001   23.779436  263188400   
3      26.799999   27.049999   26.674999   26.937500   24.112867  160423600   
4      27.307501   28.037500   27.174999   27.972500   25.039339  237458000   
...          ...         ...         ...         ...         ...        ...   
2236  189.889999  191.910004  189.880005  191.449997  191.449997   46505100   
2237  191.410004  191.520004  189.740005  190.639999  190.639999   38134500   
2238  191.490005  192.929993  190.830002  191.309998  191.309998   39617700   
2239  190.869995  190.899994  189.250000  189.970001  189.970001   24048300   
2240  189.919998  190.669998  188.899994  189.789993  189.789993   40500500   

            Date  Month  Year  day  
0     2015-01-02      1  2015    2  
1     2015-01-05      1  2015    5  
2     2015-01-06      1  2015    6  
3     2015-01-07      1  2015    7  
4     2015-01-08      1  2015    8  
...          ...    ...   ...  ...  
2236  2023-11-20     11  2023   20  
2237  2023-11-21     11  2023   21  
2238  2023-11-22     11  2023   22  
2239  2023-11-24     11  2023   24  
2240  2023-11-27     11  2023   27  

[2241 rows x 10 columns]

Using scatter plot to gain insight about closing value throughtout the dataset and analyzing pattern.

In [14]:
px.scatter(data,x=data['Date'],y=data['Close'])

Using color coding for different Years.

In [15]:
px.scatter(data,x=data['Date'],y=data['Close'],color = 'Year')

As the dataset is a timeseries data we are using open, high, lo, close columns for both input and output variables.

In [16]:
x = data[['Open','High','Low','Close']].values
y = data[['Open','High','Low','Close']].values

Splitting the data into training and testing data.

In [17]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=180)

In [18]:
n_features = x_train.shape
n_features

(1569, 4)

Creating a LSTM model based on the input and output variables.

In [19]:
# create and fit the LSTM network
model4 = Sequential()
model4.add(LSTM(120, activation='relu', return_sequences=True, input_shape=(4, 1)))
model4.add(LSTM(120, activation='relu'))
model4.add(Dense(80, activation='linear'))
model4.add(Dense(4, activation='linear'))
model4.compile(loss='MeanSquaredError', optimizer='adam', metrics=['accuracy'])
model4.fit(x, y, epochs=10, batch_size=10, verbose=2)


Epoch 1/10
225/225 - 5s - loss: 383.3407 - accuracy: 0.7569 - 5s/epoch - 23ms/step
Epoch 2/10
225/225 - 2s - loss: 0.6726 - accuracy: 0.9567 - 2s/epoch - 11ms/step
Epoch 3/10
225/225 - 5s - loss: 0.6808 - accuracy: 0.9197 - 5s/epoch - 22ms/step
Epoch 4/10
225/225 - 4s - loss: 0.6906 - accuracy: 0.8693 - 4s/epoch - 20ms/step
Epoch 5/10
225/225 - 4s - loss: 0.7216 - accuracy: 0.8782 - 4s/epoch - 17ms/step
Epoch 6/10
225/225 - 4s - loss: 0.8009 - accuracy: 0.8956 - 4s/epoch - 19ms/step
Epoch 7/10
225/225 - 3s - loss: 0.9924 - accuracy: 0.8176 - 3s/epoch - 15ms/step
Epoch 8/10
225/225 - 2s - loss: 0.9197 - accuracy: 0.7957 - 2s/epoch - 9ms/step
Epoch 9/10
225/225 - 2s - loss: 1.0413 - accuracy: 0.7993 - 2s/epoch - 8ms/step
Epoch 10/10
225/225 - 2s - loss: 0.7823 - accuracy: 0.7743 - 2s/epoch - 8ms/step


Testing model performance for the testing data.

In [20]:
y_pred = model4.predict(x_test)

22/22 [==============================] - 0s 6ms/step


In [21]:
y_pred.shape

(673, 4)

Reshaping the predicted output into the input(testing data) shape.

In [22]:
y_pred=y_pred.reshape(y_test.shape)

In [23]:
y_test.shape

(673, 4)

In [24]:
y_pred.shape

(673, 4)

Calculating the difference between actual and predicted output.

In [25]:
diff = y_test[:,2:3] - y_pred[:,2:3]

In [26]:
diff

array([[ 9.63897705e-02],
       [ 1.75323486e-02],
       [ 9.77001190e-02],
       [-9.90447998e-01],
       [-1.24568939e-02],
       [ 1.39533997e-01],
       [ 3.09692383e-01],
       [ 2.15072632e-01],
       [ 1.64951324e-01],
       [ 1.54357910e-01],
       [-6.45629883e-01],
       [ 4.23370361e-01],
       [ 4.93965149e-02],
       [ 2.58331299e-02],
       [-1.69332504e+00],
       [-1.04602814e-01],
       [ 5.52597046e-02],
       [ 2.36572266e-01],
       [-1.35480881e-01],
       [-2.82135010e-01],
       [ 5.92849731e-01],
       [-1.02081299e-02],
       [-7.20977783e-01],
       [-3.30966949e-01],
       [-7.33589172e-01],
       [-6.19468689e-02],
       [-9.19876099e-02],
       [-2.54955292e-02],
       [-1.42272949e-01],
       [ 1.68060303e-01],
       [-7.32231140e-02],
       [ 3.86314392e-02],
       [-6.56661987e-02],
       [-1.09387207e+00],
       [ 2.33291626e-01],
       [ 1.51157379e-01],
       [-1.79824829e-02],
       [ 2.53906250e-01],
       [ 6.5

Plotting te difference using scatter plot.

In [27]:
px.scatter(diff)

In [28]:
n = 10 #n represents the number of days we need forecast for.

In [29]:
last = list(data.iloc[-1,0:4]) #creating a list and adding the last day open, high, low, close values.

In [30]:
last

[189.77999877929688, 191.0800018310547, 189.39999389648438, 190.39999389648438]

In [31]:
model4.predict([last]) #predicting the forecast of next day using the last day.

1/1 [==============================] - 0s 41ms/step


array([[189.85379, 191.86646, 189.01825, 191.1513 ]], dtype=float32)

In [32]:
forecastn = [last] #ceating a new list forecastn to store the forecast of n days.

predicting for nth day forecast using predicted value of n-1th day.

In [33]:
for i in range(1,n+1):
  forecastn.append(model4.predict([forecastn[i-1]]))

1/1 [==============================] - 0s 26ms/step


In [34]:
forecastn

[[189.77999877929688,
  191.0800018310547,
  189.39999389648438,
  190.39999389648438],
 array([[189.85379, 191.86646, 189.01825, 191.1513 ]], dtype=float32),
 array([[190.10172, 192.13132, 189.26587, 191.39273]], dtype=float32),
 array([[190.35269, 192.38536, 189.51836, 191.64609]], dtype=float32),
 array([[190.60376, 192.64037, 189.77295, 191.90218]], dtype=float32),
 array([[190.85588, 192.8966 , 190.02892, 192.15987]], dtype=float32),
 array([[191.10912, 193.15395, 190.28621, 192.41895]], dtype=float32),
 array([[191.3636 , 193.41252, 190.5448 , 192.67926]], dtype=float32),
 array([[191.61935, 193.67242, 190.8045 , 192.94083]], dtype=float32),
 array([[191.87636, 193.93361, 191.06564, 193.20369]], dtype=float32),
 array([[192.13463, 194.19601, 191.32805, 193.46786]], dtype=float32)]

In [35]:
forecastn.pop(0) #Removing the last day values from the forecast.

[189.77999877929688, 191.0800018310547, 189.39999389648438, 190.39999389648438]

Seperating just closing values from the forecast.

In [36]:
extra = [arr[0][2:3] for arr in forecastn]
extra

[array([189.01825], dtype=float32),
 array([189.26587], dtype=float32),
 array([189.51836], dtype=float32),
 array([189.77295], dtype=float32),
 array([190.02892], dtype=float32),
 array([190.28621], dtype=float32),
 array([190.5448], dtype=float32),
 array([190.8045], dtype=float32),
 array([191.06564], dtype=float32),
 array([191.32805], dtype=float32)]

Converting the numpy values into float values and adding them to a list.

In [37]:
for i in range(len(extra)):
  extra[i] = list(extra[i])

In [38]:
extra1 = [arr[0] for arr in extra]

In [39]:
extra1

[189.01825,
 189.26587,
 189.51836,
 189.77295,
 190.02892,
 190.28621,
 190.5448,
 190.8045,
 191.06564,
 191.32805]

Closing value of the nth day based on the forecast.

In [40]:
print(extra1[-1])

191.32805


In [41]:
px.line(x=extra1)

In [42]:
import pickle
with open('model4.pkl', 'wb') as file:
    pickle.dump(model4, file)

In [43]:
with open('model4.pkl', 'rb') as file:
    model4 = pickle.load(file)