Importing necessary libraries.

In [1]:
import tensorflow
import pandas as pd
import plotly.express as px
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from keras.models import Sequential
from keras.layers import Dense, LSTM
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dropout
import numpy as np

In [2]:
import yfinance as yf
import datetime

Accessing today's date using datetime.

In [3]:
today = datetime.datetime.now()
today
date_today = today.strftime("%Y-%m-%d")

In [4]:
date_today

'2023-11-29'

Using 'ETH-USD' ticker to get data from start date to today.

In [5]:
ticker = 'ETH-USD'
end_date = date_today
start_date = '2015-01-01'

Downloading data and converting it into a pandas dataframe.

In [6]:
df = yf.download(ticker, start = start_date, end = end_date)

[*********************100%%**********************]  1 of 1 completed


In [7]:
df

Open         High          Low        Close    Adj Close  \
Date                                                                          
2017-11-09   308.644989   329.451996   307.056000   320.884003   320.884003   
2017-11-10   320.670990   324.717987   294.541992   299.252991   299.252991   
2017-11-11   298.585999   319.453003   298.191986   314.681000   314.681000   
2017-11-12   314.690002   319.153015   298.513000   307.907990   307.907990   
2017-11-13   307.024994   328.415009   307.024994   316.716003   316.716003   
...                 ...          ...          ...          ...          ...   
2023-11-23  2063.905518  2088.031982  2041.464233  2062.210693  2062.210693   
2023-11-24  2062.411865  2132.481201  2060.999023  2081.152100  2081.152100   
2023-11-25  2081.296143  2091.342773  2067.917236  2084.413086  2084.413086   
2023-11-26  2084.177490  2094.095947  2038.600464  2063.286133  2063.286133   
2023-11-27  2062.390869  2070.606201  1988.120361  2027.417358  2027.417358   

                 Volume  
Date                     
2017-11-09    893249984  
2017-11-10    885985984  
2017-11-11    842300992  
2017-11-12   1613479936  
2017-11-13   1041889984  
...                 ...  
2023-11-23   7828437946  
2023-11-24  12141148820  
2023-11-25   5362623390  
2023-11-26   8054814154  
2023-11-27  10574810069  

[2210 rows x 6 columns]

In [8]:
import pandas as pd
data = pd.DataFrame(df)

In [9]:
data

Open         High          Low        Close    Adj Close  \
Date                                                                          
2017-11-09   308.644989   329.451996   307.056000   320.884003   320.884003   
2017-11-10   320.670990   324.717987   294.541992   299.252991   299.252991   
2017-11-11   298.585999   319.453003   298.191986   314.681000   314.681000   
2017-11-12   314.690002   319.153015   298.513000   307.907990   307.907990   
2017-11-13   307.024994   328.415009   307.024994   316.716003   316.716003   
...                 ...          ...          ...          ...          ...   
2023-11-23  2063.905518  2088.031982  2041.464233  2062.210693  2062.210693   
2023-11-24  2062.411865  2132.481201  2060.999023  2081.152100  2081.152100   
2023-11-25  2081.296143  2091.342773  2067.917236  2084.413086  2084.413086   
2023-11-26  2084.177490  2094.095947  2038.600464  2063.286133  2063.286133   
2023-11-27  2062.390869  2070.606201  1988.120361  2027.417358  2027.417358   

                 Volume  
Date                     
2017-11-09    893249984  
2017-11-10    885985984  
2017-11-11    842300992  
2017-11-12   1613479936  
2017-11-13   1041889984  
...                 ...  
2023-11-23   7828437946  
2023-11-24  12141148820  
2023-11-25   5362623390  
2023-11-26   8054814154  
2023-11-27  10574810069  

[2210 rows x 6 columns]

Seperating date column and seperating it into new columns Month,Year and day

In [10]:
data['Date'] = pd.to_datetime(data.index).date

In [11]:
data = data.reset_index(drop=True)
data

Open         High          Low        Close    Adj Close  \
0      308.644989   329.451996   307.056000   320.884003   320.884003   
1      320.670990   324.717987   294.541992   299.252991   299.252991   
2      298.585999   319.453003   298.191986   314.681000   314.681000   
3      314.690002   319.153015   298.513000   307.907990   307.907990   
4      307.024994   328.415009   307.024994   316.716003   316.716003   
...           ...          ...          ...          ...          ...   
2205  2063.905518  2088.031982  2041.464233  2062.210693  2062.210693   
2206  2062.411865  2132.481201  2060.999023  2081.152100  2081.152100   
2207  2081.296143  2091.342773  2067.917236  2084.413086  2084.413086   
2208  2084.177490  2094.095947  2038.600464  2063.286133  2063.286133   
2209  2062.390869  2070.606201  1988.120361  2027.417358  2027.417358   

           Volume        Date  
0       893249984  2017-11-09  
1       885985984  2017-11-10  
2       842300992  2017-11-11  
3      1613479936  2017-11-12  
4      1041889984  2017-11-13  
...           ...         ...  
2205   7828437946  2023-11-23  
2206  12141148820  2023-11-24  
2207   5362623390  2023-11-25  
2208   8054814154  2023-11-26  
2209  10574810069  2023-11-27  

[2210 rows x 7 columns]

In [12]:
data['Month'] = pd.to_datetime(data['Date']).dt.month

In [13]:
data['Year'] = pd.to_datetime(data['Date']).dt.year
data['day'] = pd.to_datetime(data['Date']).dt.day

In [14]:
data

Open         High          Low        Close    Adj Close  \
0      308.644989   329.451996   307.056000   320.884003   320.884003   
1      320.670990   324.717987   294.541992   299.252991   299.252991   
2      298.585999   319.453003   298.191986   314.681000   314.681000   
3      314.690002   319.153015   298.513000   307.907990   307.907990   
4      307.024994   328.415009   307.024994   316.716003   316.716003   
...           ...          ...          ...          ...          ...   
2205  2063.905518  2088.031982  2041.464233  2062.210693  2062.210693   
2206  2062.411865  2132.481201  2060.999023  2081.152100  2081.152100   
2207  2081.296143  2091.342773  2067.917236  2084.413086  2084.413086   
2208  2084.177490  2094.095947  2038.600464  2063.286133  2063.286133   
2209  2062.390869  2070.606201  1988.120361  2027.417358  2027.417358   

           Volume        Date  Month  Year  day  
0       893249984  2017-11-09     11  2017    9  
1       885985984  2017-11-10     11  2017   10  
2       842300992  2017-11-11     11  2017   11  
3      1613479936  2017-11-12     11  2017   12  
4      1041889984  2017-11-13     11  2017   13  
...           ...         ...    ...   ...  ...  
2205   7828437946  2023-11-23     11  2023   23  
2206  12141148820  2023-11-24     11  2023   24  
2207   5362623390  2023-11-25     11  2023   25  
2208   8054814154  2023-11-26     11  2023   26  
2209  10574810069  2023-11-27     11  2023   27  

[2210 rows x 10 columns]

Using scatter plot to gain insight about closing value throughtout the dataset and analyzing pattern.

In [15]:
px.scatter(data,x=data['Date'],y=data['Close'])

Using color coding for different Years.

In [16]:
px.scatter(data,x=data['Date'],y=data['Close'],color = 'Year')

As the dataset is a timeseries data we are using open, high, lo, close columns for both input and output variables.

In [17]:
x = data[['Open','High','Low','Close']].values
y = data[['Open','High','Low','Close']].values

Splitting the data into training and testing data.

In [18]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=180)

In [19]:
n_features = x_train.shape
n_features

(1547, 4)

Creating a LSTM model based on the input and output variables.

In [20]:
# create and fit the LSTM network
model = Sequential()
model.add(LSTM(120, activation='relu', return_sequences=True, input_shape=(4, 1)))
model.add(LSTM(120, activation='relu'))
model.add(Dense(80, activation='linear'))
model.add(Dense(4, activation='linear'))
model.compile(loss='MeanSquaredError', optimizer='adam', metrics=['accuracy'])
model.fit(x, y, epochs=10, batch_size=10, verbose=2)


Epoch 1/10
221/221 - 4s - loss: 180327.3125 - accuracy: 0.7828 - 4s/epoch - 18ms/step
Epoch 2/10
221/221 - 2s - loss: 1707.5524 - accuracy: 0.9715 - 2s/epoch - 9ms/step
Epoch 3/10
221/221 - 3s - loss: 1707.4594 - accuracy: 0.9715 - 3s/epoch - 11ms/step
Epoch 4/10
221/221 - 2s - loss: 1763.7313 - accuracy: 0.9498 - 2s/epoch - 8ms/step
Epoch 5/10
221/221 - 2s - loss: 1612.1052 - accuracy: 0.9186 - 2s/epoch - 7ms/step
Epoch 6/10
221/221 - 1s - loss: 1305.1251 - accuracy: 0.9575 - 1s/epoch - 7ms/step
Epoch 7/10
221/221 - 1s - loss: 1907.4308 - accuracy: 0.9443 - 1s/epoch - 7ms/step
Epoch 8/10
221/221 - 2s - loss: 2497.8633 - accuracy: 0.7814 - 2s/epoch - 7ms/step
Epoch 9/10
221/221 - 2s - loss: 1906.8290 - accuracy: 0.9077 - 2s/epoch - 7ms/step
Epoch 10/10
221/221 - 2s - loss: 1686.1262 - accuracy: 0.8833 - 2s/epoch - 8ms/step


Testing model performance for the testing data.

In [21]:
y_pred = model.predict(x_test)

21/21 [==============================] - 0s 6ms/step


In [22]:
y_pred.shape

(663, 4)

Reshaping the predicted output into the input(testing data) shape.

In [23]:
y_pred=y_pred.reshape(y_test.shape)

In [24]:
y_test.shape

(663, 4)

In [25]:
y_pred.shape

(663, 4)

Calculating the difference between actual and predicted output.

In [26]:
diff = y_test[:,2:3] - y_pred[:,2:3]

In [27]:
diff

array([[  -4.5098114 ],
       [ -87.61962891],
       [ -68.10717773],
       [-153.23144531],
       [ -95.8717041 ],
       [  -7.28536987],
       [  -9.74569702],
       [ -88.37182617],
       [ -75.65856934],
       [  -7.1641922 ],
       [-286.54492188],
       [  -9.20713806],
       [ -76.64501953],
       [  -8.71525574],
       [-148.44262695],
       [  -7.69320679],
       [ -15.13996887],
       [ -11.21458435],
       [ -59.58459473],
       [ -10.79089355],
       [ -14.26913452],
       [ -96.46228027],
       [-115.75622559],
       [ -80.75866699],
       [ -12.67884827],
       [ -15.56968689],
       [ -45.39752197],
       [ -16.42938232],
       [-106.57568359],
       [ -86.49291992],
       [  -8.77822876],
       [ -17.16790771],
       [ -42.04812622],
       [ -29.99816895],
       [ -85.75878906],
       [ -79.50219727],
       [-109.62670898],
       [ -24.66018677],
       [ -10.13233948],
       [-200.28417969],
       [ -71.03747559],
       [-116.029

Plotting te difference using scatter plot.

In [28]:
px.scatter(diff)

In [29]:
n = 10 #n represents the number of days we need forecast for.

In [30]:
last = list(data.iloc[-1,0:4]) #creating a list and adding the last day open, high, low, close values.

In [31]:
last

[2062.390869140625, 2070.606201171875, 1988.120361328125, 2027.4173583984375]

In [32]:
model.predict([last]) #predicting the forecast of next day using the last day.

1/1 [==============================] - 0s 38ms/step


array([[2119.0173, 2139.4138, 2095.5383, 2095.2717]], dtype=float32)

In [33]:
forecastn = [last] #ceating a new list forecastn to store the forecast of n days.

predicting for nth day forecast using predicted value of n-1th day.

In [34]:
for i in range(1,n+1):
  forecastn.append(model.predict([forecastn[i-1]]))

1/1 [==============================] - 0s 23ms/step


In [35]:
forecastn

[[2062.390869140625, 2070.606201171875, 1988.120361328125, 2027.4173583984375],
 array([[2119.0173, 2139.4138, 2095.5383, 2095.2717]], dtype=float32),
 array([[2195.436 , 2215.2417, 2179.2988, 2175.912 ]], dtype=float32),
 array([[2276.9353, 2297.7683, 2261.704 , 2258.4077]], dtype=float32),
 array([[2361.8984, 2384.2698, 2345.8618, 2343.5222]], dtype=float32),
 array([[2449.9592, 2474.0215, 2432.5842, 2431.4282]], dtype=float32),
 array([[2541.0522, 2566.8223, 2522.132 , 2522.1638]], dtype=float32),
 array([[2635.1833, 2662.633 , 2614.6113, 2615.7605]], dtype=float32),
 array([[2732.3823, 2761.4648, 2710.0813, 2712.2512]], dtype=float32),
 array([[2832.6836, 2863.351 , 2808.5867, 2811.6758]], dtype=float32),
 array([[2936.1255, 2968.331 , 2910.166 , 2914.0728]], dtype=float32)]

In [36]:
forecastn.pop(0) #Removing the last day values from the forecast.

[2062.390869140625, 2070.606201171875, 1988.120361328125, 2027.4173583984375]

Seperating just closing values from the forecast.

In [37]:
extra = [arr[0][2:3] for arr in forecastn]
extra

[array([2095.5383], dtype=float32),
 array([2179.2988], dtype=float32),
 array([2261.704], dtype=float32),
 array([2345.8618], dtype=float32),
 array([2432.5842], dtype=float32),
 array([2522.132], dtype=float32),
 array([2614.6113], dtype=float32),
 array([2710.0813], dtype=float32),
 array([2808.5867], dtype=float32),
 array([2910.166], dtype=float32)]

Converting the numpy values into float values and adding them to a list.

In [38]:
for i in range(len(extra)):
  extra[i] = list(extra[i])

In [39]:
extra1 = [arr[0] for arr in extra]

In [40]:
extra1

[2095.5383,
 2179.2988,
 2261.704,
 2345.8618,
 2432.5842,
 2522.132,
 2614.6113,
 2710.0813,
 2808.5867,
 2910.166]

Closing value of the nth day based on the forecast.

In [41]:
print(extra1[-1])

2910.166


In [42]:
px.line(x=extra1)

In [43]:
models = {
    "lstm":model
}

In [44]:
import pickle
import pickle
with open('model1.pkl', 'wb') as file:
    pickle.dump(model, file)

In [45]:
with open('model1.pkl', 'rb') as file:
    model1 = pickle.load(file)