Importing necessary libraries.

In [1]:
import tensorflow
import pandas as pd
import plotly.express as px
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from keras.models import Sequential
from keras.layers import Dense, LSTM
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dropout
import numpy as np

In [2]:
import yfinance as yf
import datetime

Accessing today's date using datetime.

In [3]:
today = datetime.datetime.now()
today
date_today = today.strftime("%Y-%m-%d")

In [4]:
date_today

'2023-11-29'

Using 'ETH-USD' ticker to get data from start date to today.

In [5]:
ticker = ' MSFT'
end_date = date_today
start_date = '2015-01-01'

Downloading data and converting it into a pandas dataframe.

In [6]:
df = yf.download(ticker, start = start_date, end = end_date)

[*********************100%%**********************]  1 of 1 completed


In [7]:
df

Open        High         Low       Close   Adj Close  \
Date                                                                     
2015-01-02   46.660000   47.419998   46.540001   46.759998   40.452740   
2015-01-05   46.369999   46.730000   46.250000   46.330002   40.080742   
2015-01-06   46.380001   46.750000   45.540001   45.650002   39.492474   
2015-01-07   45.980000   46.459999   45.490002   46.230000   39.994225   
2015-01-08   46.750000   47.750000   46.720001   47.590000   41.170780   
...                ...         ...         ...         ...         ...   
2023-11-21  375.670013  376.220001  371.119995  373.070007  373.070007   
2023-11-22  378.000000  379.790009  374.970001  377.850006  377.850006   
2023-11-24  377.329987  377.970001  375.140015  377.429993  377.429993   
2023-11-27  376.779999  380.640015  376.200012  378.609985  378.609985   
2023-11-28  378.350006  383.000000  378.160004  382.700012  382.700012   

              Volume  
Date                  
2015-01-02  27913900  
2015-01-05  39673900  
2015-01-06  36447900  
2015-01-07  29114100  
2015-01-08  29645200  
...              ...  
2023-11-21  28423100  
2023-11-22  23345300  
2023-11-24  10176600  
2023-11-27  22179200  
2023-11-28  20429400  

[2242 rows x 6 columns]

In [8]:
import pandas as pd
data = pd.DataFrame(df)

In [9]:
data

Open        High         Low       Close   Adj Close  \
Date                                                                     
2015-01-02   46.660000   47.419998   46.540001   46.759998   40.452740   
2015-01-05   46.369999   46.730000   46.250000   46.330002   40.080742   
2015-01-06   46.380001   46.750000   45.540001   45.650002   39.492474   
2015-01-07   45.980000   46.459999   45.490002   46.230000   39.994225   
2015-01-08   46.750000   47.750000   46.720001   47.590000   41.170780   
...                ...         ...         ...         ...         ...   
2023-11-21  375.670013  376.220001  371.119995  373.070007  373.070007   
2023-11-22  378.000000  379.790009  374.970001  377.850006  377.850006   
2023-11-24  377.329987  377.970001  375.140015  377.429993  377.429993   
2023-11-27  376.779999  380.640015  376.200012  378.609985  378.609985   
2023-11-28  378.350006  383.000000  378.160004  382.700012  382.700012   

              Volume  
Date                  
2015-01-02  27913900  
2015-01-05  39673900  
2015-01-06  36447900  
2015-01-07  29114100  
2015-01-08  29645200  
...              ...  
2023-11-21  28423100  
2023-11-22  23345300  
2023-11-24  10176600  
2023-11-27  22179200  
2023-11-28  20429400  

[2242 rows x 6 columns]

Seperating date column and seperating it into new columns Month,Year and day

In [10]:
data['Date'] = pd.to_datetime(data.index).date

In [11]:
data = data.reset_index(drop=True)
data

Open        High         Low       Close   Adj Close    Volume  \
0      46.660000   47.419998   46.540001   46.759998   40.452740  27913900   
1      46.369999   46.730000   46.250000   46.330002   40.080742  39673900   
2      46.380001   46.750000   45.540001   45.650002   39.492474  36447900   
3      45.980000   46.459999   45.490002   46.230000   39.994225  29114100   
4      46.750000   47.750000   46.720001   47.590000   41.170780  29645200   
...          ...         ...         ...         ...         ...       ...   
2237  375.670013  376.220001  371.119995  373.070007  373.070007  28423100   
2238  378.000000  379.790009  374.970001  377.850006  377.850006  23345300   
2239  377.329987  377.970001  375.140015  377.429993  377.429993  10176600   
2240  376.779999  380.640015  376.200012  378.609985  378.609985  22179200   
2241  378.350006  383.000000  378.160004  382.700012  382.700012  20429400   

            Date  
0     2015-01-02  
1     2015-01-05  
2     2015-01-06  
3     2015-01-07  
4     2015-01-08  
...          ...  
2237  2023-11-21  
2238  2023-11-22  
2239  2023-11-24  
2240  2023-11-27  
2241  2023-11-28  

[2242 rows x 7 columns]

In [12]:
data['Month'] = pd.to_datetime(data['Date']).dt.month

In [13]:
data['Year'] = pd.to_datetime(data['Date']).dt.year
data['day'] = pd.to_datetime(data['Date']).dt.day

In [14]:
data

Open        High         Low       Close   Adj Close    Volume  \
0      46.660000   47.419998   46.540001   46.759998   40.452740  27913900   
1      46.369999   46.730000   46.250000   46.330002   40.080742  39673900   
2      46.380001   46.750000   45.540001   45.650002   39.492474  36447900   
3      45.980000   46.459999   45.490002   46.230000   39.994225  29114100   
4      46.750000   47.750000   46.720001   47.590000   41.170780  29645200   
...          ...         ...         ...         ...         ...       ...   
2237  375.670013  376.220001  371.119995  373.070007  373.070007  28423100   
2238  378.000000  379.790009  374.970001  377.850006  377.850006  23345300   
2239  377.329987  377.970001  375.140015  377.429993  377.429993  10176600   
2240  376.779999  380.640015  376.200012  378.609985  378.609985  22179200   
2241  378.350006  383.000000  378.160004  382.700012  382.700012  20429400   

            Date  Month  Year  day  
0     2015-01-02      1  2015    2  
1     2015-01-05      1  2015    5  
2     2015-01-06      1  2015    6  
3     2015-01-07      1  2015    7  
4     2015-01-08      1  2015    8  
...          ...    ...   ...  ...  
2237  2023-11-21     11  2023   21  
2238  2023-11-22     11  2023   22  
2239  2023-11-24     11  2023   24  
2240  2023-11-27     11  2023   27  
2241  2023-11-28     11  2023   28  

[2242 rows x 10 columns]

Using scatter plot to gain insight about closing value throughtout the dataset and analyzing pattern.

In [15]:
px.scatter(data,x=data['Date'],y=data['Close'])

Using color coding for different Years.

In [16]:
px.scatter(data,x=data['Date'],y=data['Close'],color = 'Year')

As the dataset is a timeseries data we are using open, high, lo, close columns for both input and output variables.

In [17]:
x = data[['Open','High','Low','Close']].values
y = data[['Open','High','Low','Close']].values

Splitting the data into training and testing data.

In [18]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=180)

In [19]:
n_features = x_train.shape
n_features

(1569, 4)

Creating a LSTM model based on the input and output variables.

In [20]:
# create and fit the LSTM network
model5 = Sequential()
model5.add(LSTM(120, activation='relu', return_sequences=True, input_shape=(4, 1)))
model5.add(LSTM(120, activation='relu'))
model5.add(Dense(80, activation='linear'))
model5.add(Dense(4, activation='linear'))
model5.compile(loss='MeanSquaredError', optimizer='adam', metrics=['accuracy'])
model5.fit(x, y, epochs=10, batch_size=10, verbose=2)


Epoch 1/10
225/225 - 9s - loss: 1211.2563 - accuracy: 0.7774 - 9s/epoch - 42ms/step
Epoch 2/10
225/225 - 3s - loss: 2.1930 - accuracy: 0.9211 - 3s/epoch - 15ms/step
Epoch 3/10
225/225 - 2s - loss: 2.4432 - accuracy: 0.9090 - 2s/epoch - 8ms/step
Epoch 4/10
225/225 - 2s - loss: 2.3511 - accuracy: 0.8720 - 2s/epoch - 9ms/step
Epoch 5/10
225/225 - 2s - loss: 3.3063 - accuracy: 0.7507 - 2s/epoch - 8ms/step
Epoch 6/10
225/225 - 2s - loss: 3.7821 - accuracy: 0.7266 - 2s/epoch - 8ms/step
Epoch 7/10
225/225 - 2s - loss: 2.6342 - accuracy: 0.8015 - 2s/epoch - 10ms/step
Epoch 8/10
225/225 - 3s - loss: 4.0694 - accuracy: 0.7698 - 3s/epoch - 12ms/step
Epoch 9/10
225/225 - 1s - loss: 3.3534 - accuracy: 0.7021 - 1s/epoch - 6ms/step
Epoch 10/10
225/225 - 1s - loss: 3.4171 - accuracy: 0.8029 - 1s/epoch - 6ms/step


Testing model performance for the testing data.

In [21]:
y_pred = model5.predict(x_test)

22/22 [==============================] - 0s 5ms/step


In [22]:
y_pred.shape

(673, 4)

Reshaping the predicted output into the input(testing data) shape.

In [23]:
y_pred=y_pred.reshape(y_test.shape)

In [24]:
y_test.shape

(673, 4)

In [25]:
y_pred.shape

(673, 4)

Calculating the difference between actual and predicted output.

In [26]:
diff = y_test[:,2:3] - y_pred[:,2:3]

In [27]:
diff

array([[ 3.58032227e-01],
       [-1.95327759e-01],
       [ 1.36596680e-01],
       [-8.95050049e-01],
       [ 2.92587280e-02],
       [ 2.40859985e-01],
       [ 1.53581238e+00],
       [ 4.63714600e-01],
       [ 8.90220642e-01],
       [ 6.98287964e-01],
       [-3.66676331e-01],
       [ 9.37393188e-01],
       [ 4.69718933e-01],
       [ 4.19090271e-01],
       [-5.38246155e+00],
       [ 3.15826416e-01],
       [ 5.99884033e-01],
       [ 1.02709961e+00],
       [-3.89671326e-02],
       [ 3.99688721e-01],
       [ 1.39772034e+00],
       [-2.72434235e-01],
       [-2.86956787e+00],
       [ 1.10641479e-01],
       [-1.40013123e+00],
       [ 3.63449097e-01],
       [ 1.48753357e+00],
       [-9.91039276e-01],
       [ 4.07691956e-01],
       [ 1.12458801e+00],
       [ 3.71345520e-01],
       [-2.36434937e-02],
       [-1.18942261e-02],
       [-8.46817017e-01],
       [ 7.41836548e-01],
       [ 5.28266907e-01],
       [-2.21347809e-01],
       [ 4.43618774e-01],
       [ 2.1

Plotting te difference using scatter plot.

In [28]:
px.scatter(diff)

In [29]:
n = 10 #n represents the number of days we need forecast for.

In [30]:
last = list(data.iloc[-1,0:4]) #creating a list and adding the last day open, high, low, close values.

In [31]:
last

[378.3500061035156, 383.0, 378.1600036621094, 382.70001220703125]

In [32]:
model5.predict([last]) #predicting the forecast of next day using the last day.

1/1 [==============================] - 0s 37ms/step


array([[376.21106, 377.4375 , 376.41275, 380.28775]], dtype=float32)

In [33]:
forecastn = [last] #ceating a new list forecastn to store the forecast of n days.

predicting for nth day forecast using predicted value of n-1th day.

In [34]:
for i in range(1,n+1):
  forecastn.append(model5.predict([forecastn[i-1]]))

1/1 [==============================] - 0s 23ms/step


In [35]:
forecastn

[[378.3500061035156, 383.0, 378.1600036621094, 382.70001220703125],
 array([[376.21106, 377.4375 , 376.41275, 380.28775]], dtype=float32),
 array([[373.1292 , 374.2382 , 373.4195 , 377.17496]], dtype=float32),
 array([[370.0611 , 371.1599 , 370.33963, 374.0697 ]], dtype=float32),
 array([[367.01462, 368.1091 , 367.2752 , 370.98456]], dtype=float32),
 array([[363.98956, 365.0803 , 364.2323 , 367.9209 ]], dtype=float32),
 array([[360.98596, 362.0725 , 361.2109 , 364.87885]], dtype=float32),
 array([[358.00323, 359.08615, 358.211  , 361.85803]], dtype=float32),
 array([[355.04178, 356.1205 , 355.2324 , 358.85855]], dtype=float32),
 array([[352.10095, 353.17578, 352.2749 , 355.87994]], dtype=float32),
 array([[349.18073, 350.25153, 349.3383 , 352.92227]], dtype=float32)]

In [36]:
forecastn.pop(0) #Removing the last day values from the forecast.

[378.3500061035156, 383.0, 378.1600036621094, 382.70001220703125]

Seperating just closing values from the forecast.

In [37]:
extra = [arr[0][2:3] for arr in forecastn]
extra

[array([376.41275], dtype=float32),
 array([373.4195], dtype=float32),
 array([370.33963], dtype=float32),
 array([367.2752], dtype=float32),
 array([364.2323], dtype=float32),
 array([361.2109], dtype=float32),
 array([358.211], dtype=float32),
 array([355.2324], dtype=float32),
 array([352.2749], dtype=float32),
 array([349.3383], dtype=float32)]

Converting the numpy values into float values and adding them to a list.

In [38]:
for i in range(len(extra)):
  extra[i] = list(extra[i])

In [39]:
extra1 = [arr[0] for arr in extra]

In [40]:
extra1

[376.41275,
 373.4195,
 370.33963,
 367.2752,
 364.2323,
 361.2109,
 358.211,
 355.2324,
 352.2749,
 349.3383]

Closing value of the nth day based on the forecast.

In [41]:
print(extra1[-1])

349.3383


In [42]:
px.line(x=extra1)

In [43]:
import pickle
with open('model5.pkl', 'wb') as file:
    pickle.dump(model5, file)

In [44]:
with open('model5.pkl', 'rb') as file:
    model5 = pickle.load(file)